const lesson=(n,title,body)=>`<details class="lesson" ${n===1?'open':''}><summary><span>${String(n).padStart(2,'0')}</span>${title}</summary><div class="lesson-body">${body}</div></details>`;
const tomorrowId='vat-inclusive-price';
const block=(title,body)=>'<section class="panel"><h2>'+title+'</h2>'+body+'</section>';
function start(){const r=D.find(x=>x.id===tomorrowId);main.innerHTML=head('Your working desk','Judy, start with this post.','One useful lesson before the website launch. Everything else stays in preparation.')+
'<section class="mission"><div><span class="pill">Tomorrow · CEO review needed</span><h2>Price includes VAT.<br>How much is the VAT?</h2><p class="arabic" dir="rtl">١٬١٥٠ ريال شاملة الضريبة: مبلغ الضريبة ١٥٠ ريال، وليس ١٧٢٫٥٠.</p><p>Three slides. One useful calculation. No website link, boost or sales pitch.</p><a class="button primary" href="#tomorrow">Prepare tomorrow’s post →</a></div>'+(r?.images[0]?'<img src="'+r.images[0].path+'" alt="VAT-inclusive price worked example">':'')+'</section><div class="journey"><a href="#tomorrow"><b>1 / Prepare</b><span>Images, copy and review</span></a><a href="#publish"><b>2 / Publish</b><span>Step-by-step instructions</span></a><a href="#learn"><b>3 / Learn</b><span>Replies and results</span></a></div><div class="grid">'+
block('Your first publishing lesson','<p>Keep the post pack open while you follow the guide. Learn file order, crop, caption, accessibility and final checks.</p><a href="#publish">Follow the beginner guide →</a>')+
block('Google Ads, after launch','<p>Learn the actual account screens, keywords, ad copy, budgets and conversion checks. The inspected account reports no ads running.</p><a href="#ads">Open the campaign walkthrough →</a>')+
block('Create together','<p>Bring Omar a real reader question, one example and one intended action. Use the brief and results worksheets.</p><a href="#brief">Build a useful content brief →</a>')+'</div>';}
function tomorrow(){const r=D.find(x=>x.id===tomorrowId);main.innerHTML=head('Tomorrow’s publishing pack','One question. A complete answer.','Recommended: one Instagram carousel with three images. No other pre-launch posts are planned.')+
'<div class="notice">CEO approval is not recorded. Publishing is manual. If review is incomplete, hold this post; do not substitute an older campaign.</div>'+
block('Why this topic before launch','<p>The answer fits entirely inside the post. A concrete arithmetic mistake makes the lesson immediately understandable. This is an editorial choice, not a verified search-volume or reach forecast.</p><p><b>Scope:</b> a hypothetical single supply, wholly subject to 15%, without discounts or mixed rates. This does not determine recoverable VAT or the amount due on a return.</p>')+
'<div class="gallery">'+(r?.images||[]).map(i=>'<figure><img src="'+i.path+'" alt="'+esc(i.alt)+'"><a class="button" href="'+i.path+'" download>Download '+esc(i.name)+'</a><figcaption dir="rtl">'+esc(i.alt)+'</figcaption></figure>').join('')+'</div>'+
block('Caption for review','<pre class="copy" dir="rtl" id="tomorrow-copy">'+esc(r?.captions['Instagram Arabic']||'')+'</pre><button id="copy-tomorrow">Copy caption</button><span role="status" id="copied"></span><p><a href="inclusive-vat-pack.zip" download>Download the complete pack ↓</a> · <a href="#publish">Exact posting steps →</a></p>')+
block('CEO: review these specific points','<ul><li>The full supply is assumed subject to 15%.</li><li>1,000 + 150 = 1,150; 1,150 × 15 ÷ 115 = 150.</li><li>The copy does not imply every Saudi supply has the same treatment.</li><li>The Arabic, numbers and qualification remain readable on a phone.</li><li>Approve the final images AND caption together; return edits to Omar.</li></ul><p>Rate and applicability source: <a href="https://zatca.gov.sa/en/HelpCenter/guidelines/Documents/Amendments-to-the-Implementing-Regulation-of-%28VAT%29.PDF">ZATCA guidance, section 1.3</a>. The numbers and rearranged formula are our arithmetic illustration.</p>')+
block('Judy’s posting decision','<p>Suggested test slot: <b>19:30 Saudi time</b>, when Judy can monitor replies. This is a practical starting point, not a finding from Mada’s audience analytics. Agree another staffed slot if necessary. Publish only the approved carousel; do not boost it.</p><p>After posting, send Omar the post URL and a screenshot of its crop. Record results after 24 hours and again after seven days.</p>');
document.querySelector('#copy-tomorrow').onclick=async()=>{try{await navigator.clipboard.writeText(r.captions['Instagram Arabic']);document.querySelector('#copied').textContent=' Copied';}catch{document.querySelector('#copied').textContent=' Select and copy manually.'}};}
function publishGuide(){main.innerHTML=head('Learn / publishing','From downloaded images to a clean post.','Work in order. Interface labels may vary by app version; use the visible equivalent.')+
lesson(1,'Prepare files and approval','<ol><li>Download the three numbered PNGs from Tomorrow’s post and keep them together.</li><li>Send final images, caption and source scope to the CEO using your normal review channel. Record the exact approved version privately.</li><li>Read every slide on your phone. Check Arabic, formulas, margins and numbering. Do not publish a cropped qualification.</li><li>Confirm Mada is the posting identity, not your personal profile.</li></ol><p class="example">Ready = final images + matching caption + recorded review + time to answer comments. A finished design alone is not ready.</p>')+
lesson(2,'Instagram: publish the carousel','<ol><li>In Mada’s account choose Create / +, then Post.</li><li>Choose multiple photos and select 01 → 02 → 03. The first image is the cover.</li><li>Inspect the feed crop of EACH slide. Keep the numbers and scope note visible. Avoid filters that reduce contrast.</li><li>Paste the reviewed Arabic caption. Preserve the hypothetical-example wording. No website link or “link in bio” here.</li><li>Where Accessibility / Write alt text is available, use the image descriptions in the pack. If absent, retain the explanatory caption.</li><li>Preview again. After approval choose Share. Skip boost and paid promotion options.</li><li>Open the published post as a viewer. Swipe all slides and copy the URL for Omar.</li></ol><p class="example">If 02 appears first, cancel before publishing and reorder. If the formula is cut off, fix the crop before sharing.</p>')+
lesson(3,'LinkedIn: adapt future content','<p>Use this after launch; do not add another pre-launch post.</p><ol><li>Switch to Mada’s Page and confirm the posting identity.</li><li>Choose Start a post and add reviewed images. A multi-image post differs from a document carousel; choose a reviewed PDF for a document post.</li><li>Open with a workplace question, then an example, its limitation and one next step.</li><li>For article campaigns use the matching live article and inspect the link preview.</li><li>Preview, publish after review, and record the post URL.</li></ol><p class="example">Specific: “A sales report and VAT report can disagree because their periods differ. Check scope before investigating the number.” Vague: “We provide the best solutions.”</p><a href="https://business.linkedin.com/content/dam/lem/business/en/advertise/linkedin-pages/lms-linkedin-page-posting-best-practices-one-pager.pdf">LinkedIn Page guidance ↗</a>')+
lesson(4,'Practical ways to improve reach','<ul><li><b>Show the question immediately.</b> A worked price example beats “Important tax tips”.</li><li><b>Teach one thing.</b> Save the second question for another brief.</li><li><b>Make it useful without a click.</b> The answer must be in the post.</li><li><b>Use relevant terms.</b> A small relevant hashtag set is enough to test; no hashtag count guarantees reach.</li><li><b>Use a staffed posting window.</b> Compare Mada’s actual Insights across similar posts.</li><li><b>Answer real questions.</b> Never request invoices or private tax details in comments.</li><li><b>Check Account Status.</b> Do not assume low reach proves suppression.</li></ul><p>Open Professional Dashboard → Best Practices when available for personalised guidance.</p><a href="https://about.fb.com/news/2024/10/best-practices-education-hub-creators-instagram/">Instagram Best Practices ↗</a>');}
function learnGuide(){main.innerHTML=head('After publishing','Turn questions into the next lesson.','Record what people understood, what confused them and what you will improve.')+
block('Replies Judy can adapt','<div class="reply"><b>“Why divide by 115?”</b><p dir="rtl">لأن الإجمالي في المثال يمثل ١٠٠٪ من السعر الأساسي + ١٥٪ ضريبة، أي ١١٥٪. لذلك نستخرج جزء الضريبة بضرب الإجمالي في ١٥ ÷ ١١٥.</p></div><div class="reply"><b>“Does this apply to every invoice?”</b><p dir="rtl">المثال يفترض أن كامل المبلغ خاضع لنسبة ١٥٪. إذا اختلفت النسبة أو احتوت الفاتورة على بنود بمعالجات مختلفة، فلا نطبق المثال على الإجمالي مباشرة.</p></div><div class="reply"><b>“Can I deduct this VAT?”</b><p dir="rtl">المثال يوضح الحساب فقط، ولا يحدد أهلية خصم الضريبة. تعتمد المعالجة على تفاصيل العملية والمتطلبات المنطبقة. يرجى عدم مشاركة الفواتير أو البيانات الخاصة في التعليقات.</p><p>Escalate case-specific questions privately to Omar/CEO. Do not promise a deduction.</p></div>')+
block('Record useful evidence','<div class="table-scroll"><table><tr><th>Signal</th><th>Meaning</th><th>Next action</th></tr><tr><td>Reach</td><td>Accounts exposed; not enquiries</td><td>Compare similar posts</td></tr><tr><td>Saves / shares</td><td>Possible usefulness; not proven sales</td><td>Identify the lesson people kept</td></tr><tr><td>Repeated questions</td><td>A possible explanation gap</td><td>Use the general question in a new brief</td></tr><tr><td>Qualified enquiry</td><td>A relevant request confirmed by Mada</td><td>Record source privately; never infer from a like</td></tr></table></div><p>No website link means article visits are not tomorrow’s success measure. Small samples support observations, not firm winners.</p><a class="button" href="results-template.csv" download>Download results worksheet</a>')+
block('Make one informed change','<p class="example">“Several readers asked why 115 is used. Next we will show the 100 + 15 breakdown more clearly.” This connects the next creative decision to evidence.</p><p>Compare several similar posts in two staffed windows. Record topic, format and organic versus paid distribution. Do not change five variables at once.</p><a href="https://www.linkedin.com/business/marketing/blog/linkedin-ads/whats-the-best-time-to-post-on-linkedin">LinkedIn: test your publishing times ↗</a>');}
function briefGuide(){main.innerHTML=head('Create with Omar','Bring a question. Build a complete brief.','Keep customer documents and identifiers out of this public desk.')+
block('Tomorrow’s brief, filled in','<dl class="status-list"><div><dt>Reader</dt><dd>Business owner or finance assistant checking an inclusive price</dd></div><div><dt>Question</dt><dd>How much VAT is inside SAR 1,150 at 15%?</dd></div><div><dt>Answer</dt><dd>SAR 150 under the stated assumptions</dd></div><div><dt>Format</dt><dd>Three slides: mistake → breakdown → formula</dd></div><div><dt>Action</dt><dd>Save the explanation</dd></div><div><dt>Evidence</dt><dd>ZATCA rate guidance + checked arithmetic</dd></div><div><dt>Review</dt><dd>CEO approves final slides and caption</dd></div></dl><a class="button" href="content-brief.md" download>Download blank brief</a>')+
block('Send this in our next content session',`<pre class="copy">Reader:
Real general question we heard:
What the reader should understand:
Example without private data:
Source or clarification needed:
One action after reading:
Format and channel:
Website destination ready? Yes / No / Not needed
CEO feedback:
What the previous post taught us:</pre>`)+
block('Choose the format for the job','<ul><li><b>One calculation:</b> short carousel with a worked example.</li><li><b>A complex process:</b> complete article first, then a focused carousel.</li><li><b>A screen demonstration:</b> short video with a reviewed script, safe real screens and readable captions.</li><li><b>Learn the reader’s problem:</b> a Story question with a plan to use the responses.</li></ul><p>Video is useful when motion or demonstration adds understanding. It is not mandatory for every topic.</p>')+
block('Plain-language glossary','<p><b>Hook:</b> the opening reason to pay attention. <b>CTA:</b> one next action. <b>Landing page:</b> the page an ad opens. <b>UTM:</b> a tag identifying an external visit’s source. <b>Conversion:</b> a configured tracked action; its name does not prove a lead. <b>CTR:</b> clicks ÷ impressions. <b>CPC:</b> cost ÷ clicks.</p>');}
function newCalendar(){main.innerHTML=head('Editorial sequence','One pre-launch post. A queue after it.','Working stages, not automatically scheduled dates.')+
block('Before the website is ready','<h3>Tomorrow: VAT inside the price</h3><p>Instagram · proposed 19:30 Saudi time · pending CEO approval. No website link and no boost.</p><a class="button" href="#tomorrow">Open the post pack</a><p>All other posts remain on hold. Prepare files, review content and learn the account meanwhile.</p>')+
block('After launch is verified','<ol><li>Check the article on mobile and verify the company receives form submissions.</li><li>Review Zakat file preparation and choose one organic channel first.</li><li>Refine VAT reconciliation from reader questions, then publish its approved article-led post.</li><li>Verify the invoice article before using its prepared links.</li><li>Assess a Google Search pilot only after conversion checks and media-budget approval.</li></ol><a href="#campaigns">Open preparation library →</a>');}
