
function growthLab(){main.innerHTML=head('Reach laboratory','Make the lesson worth sharing. Then test it.','Virality is an outcome we cannot promise. Our controllable work is relevance, clarity, originality and a useful reason to save or share.')+
'<div class="journey"><div><b>Recognise</b><span>The reader sees their problem</span></div><div><b>Understand</b><span>A specific example delivers the answer</span></div><div><b>Keep or share</b><span>The lesson helps them or a colleague</span></div></div>'+
block('Hook workshop: replace vague openings','<div class="table-scroll"><table><tr><th>Weak opening</th><th>Specific draft</th><th>Why test it</th></tr><tr><td>معلومات مهمة عن الضريبة</td><td dir="rtl">السعر ١٬١٥٠ ريال شامل الضريبة. كم مبلغ الضريبة داخله؟</td><td>A visible calculation and clear question</td></tr><tr><td>نصائح لتنظيم الملفات</td><td dir="rtl">لديك ثلاث نسخ نهائية من الملف. أي نسخة سترسل للمراجع؟</td><td>A recognisable handoff problem</td></tr><tr><td>خدمات الفوترة الإلكترونية</td><td dir="rtl">هل امتداد PDF وحده يخبرك أن الفاتورة مستوفية للمتطلبات؟</td><td>A precise question; answer needs current source review</td></tr></table></div><p>Deliver the answer early. Do not make the viewer swipe through filler, fear or a sales pitch to get it.</p>')+
block('Build a post with a job for every frame','<div class="storyboard"><div><small>01 / QUESTION</small><b>Show the situation</b><p>A price, two reports or conflicting versions. Use enough context to recognise it.</p></div><div><small>02 / EXPLANATION</small><b>Make the relationship visible</b><p>A decomposition, matched columns or annotated example. Each visual must teach something.</p></div><div><small>03 / APPLICATION</small><b>Give a usable next action</b><p>Formula, checklist or question to ask. Keep the scope visible. Choose one CTA.</p></div></div><p>For a longer carousel, add slides only when they answer a necessary question. Decorative repetition is not explanation.</p>')+
block('A short-video storyboard you can actually produce','<p><b>Future adaptation after the pre-launch hold:</b> reuse the reviewed inclusive-VAT lesson, not new tax claims.</p><div class="table-scroll"><table><tr><th>Window</th><th>Visual</th><th>Spoken / on-screen purpose</th></tr><tr><td>0–3s</td><td>Inclusive price appears</td><td dir="rtl">١٬١٥٠ ريال شاملة الضريبة. هل الضريبة ١٧٢٫٥٠؟</td></tr><tr><td>3–9s</td><td>Split total into 1000 + 150</td><td>Explain why the percentage starts from the base</td></tr><tr><td>9–16s</td><td>Build 1150 × 15 ÷ 115</td><td>Show each step, keeping numbers readable</td></tr><tr><td>16–22s</td><td>Hold formula and scope</td><td>Save CTA and full15% hypothetical condition</td></tr></table></div><p>These are editing windows, not a platform-optimal duration claim. Review spoken Arabic, subtitles, contrast, safe margins and music rights. A real demonstration is preferable when motion helps understanding. Do not invent a spokesperson or office.</p>')+
block('Choose a controlled experiment','<label>What do you want to learn? <select id="growth-test"><option value="cover">Which cover explains the topic?</option><option value="format">Does demonstration improve understanding?</option><option value="timing">Which staffed time fits our audience?</option></select></label><div id="growth-experiment" class="example"></div>')+
block('Useful habits versus myths','<ul><li><b>Do:</b> write original explanations, use a real example, preserve technical limits and describe visuals accessibly.</li><li><b>Do:</b> inspect Professional Dashboard → Best Practices and Account Status when available.</li><li><b>Do:</b> answer genuine questions and use them to improve the next article.</li><li><b>Avoid:</b> bought followers, engagement groups, repetitive comments and irrelevant trend-jacking.</li><li><b>Do not assume:</b> a magic hashtag count, guaranteed first-hour boost, universal best time or fixed posting frequency.</li><li><b>Do not confuse:</b> a widely shared arithmetic post with proven demand for a paid consultation.</li></ul><p>Instagram provides personalised guidance across creation, engagement and reach through its <a href="https://about.fb.com/news/2024/10/best-practices-education-hub-creators-instagram/">Best Practices hub</a>. Recommendation eligibility is separate from guaranteed distribution: <a href="https://about.fb.com/news/2020/08/recommendation-guidelines/">Meta recommendation guidelines</a>.</p>')+
block('Decide from evidence','<p>Record raw counts first: reach, saves, shares, substantive questions and confirmed relevant enquiries. Optional comparison: saves ÷ reach ×100, with its denominator shown. Compare the same observation window and format; separate paid distribution.</p><p>Small differences across a few posts can be noise. Keep / revise / stop should include an explanation and a next test, not a claim that an algorithm has been solved.</p>');
const tests={cover:'Hypothesis: a worked-number cover communicates the lesson better than a general headline. Show two drafts to three willing colleagues without explaining them. Ask what they expect to learn. Choose the clearer draft before publishing. This is a comprehension check, not an audience experiment.',format:'Hypothesis: an animated breakdown answers the repeated “why115?” question more clearly. After launch and approval, compare a short demonstration with a similar static lesson. Record questions showing understanding, saves and reach. Different distribution and topics are confounders; do not declare a causal winner.',timing:'Hypothesis: a staffed evening slot fits Instagram readers better than another available window. Start with19:30Saudi as an operational choice, compare with another staffed slot across several comparable approved posts, and consult actual follower activity. Do not add pre-launch posts to fill this experiment.'};
const update=()=>document.querySelector('#growth-experiment').textContent=tests[document.querySelector('#growth-test').value];document.querySelector('#growth-test').onchange=update;update();
}
const AD_STEPS=[
['Question','A finance employee searches for a VAT reconciliation explanation.','Our targeting starts with the reader’s question, not a generic list of every Mada service.','What question should this ad answer?'],
['Keyword','A small related group may match that search.','Exact and phrase keywords can include close variants and related intent. Review actual search terms; they are not identical to keywords.','Would this query fit the article?'],
['Ad','The ad promises a practical explanation.','Use Mada as the advertiser. The promise must be delivered on the landing page. Standard responsive Search ads are primarily text.','Does the headline promise what the article contains?'],
['Article','The visitor gets the answer near the top.','Show a useful example, official sources and limitations. Add an optional relevant service link after the explanation.','Can the reader learn without contacting us?'],
['Enquiry','A reader who needs help submits a form.','Clear labels, relevant scope, working company inbox and an honest response expectation matter. Do not count a click on Submit as a successful enquiry.','Did the submission actually succeed?'],
['Measurement','Mada confirms the request is relevant.','Separate page reading, form success, call clicks and qualified enquiries. Attribution has limits; reconcile tracking with real business records privately.','Was it a relevant enquiry, and what supports its source?']
];
function adsLab(){main.innerHTML=head('Google Ads / visual practice','Understand the journey before touching the budget.','Practice here without creating campaigns or spending. Then use the account walkthrough for the real controls.')+
'<div class="flow-tabs" role="group" aria-label="Advertising journey">'+AD_STEPS.map((s,i)=>'<button data-stage="'+i+'">'+(i+1)+'. '+s[0]+'</button>').join('')+'</div><section id="stage-detail" class="stage-detail" aria-live="polite"></section>'+
block('Where the real controls live','<div class="account-grid"><figure><img src="google-goals-navigation.png" alt="Observed Mada Goals and Conversions navigation"><figcaption>Observed account navigation, not a live feed.</figcaption></figure><div><h3>Check Goals before trusting results</h3><p>Goals → Conversions → Summary → View all conversion actions. Read name, source, tracking status, optimisation and count together.</p><p>The prior inspection found the Form action imported from GA4, set to Primary and Every, with Awaiting conversions. That needs validation; inactivity alone does not prove a broken form.</p><a href="#ads">Open all nine account lessons →</a></div></div><figure><img class="wide-screen" src="google-objective.png" alt="Actual campaign objective selection options"><figcaption>The inspected campaign objective screen. Objective selection does not replace correct conversion tracking.</figcaption></figure>')+
block('Budget practice: see what the allowance can buy','<p><b>Hypothetical arithmetic only.</b> These inputs are not forecasts, live account data or recommended budget settings. No enquiry-rate assumption is supplied.</p><div class="sim-inputs"><label>Media amount for illustration (SAR)<input id="sim-budget" type="number" min="0" max="100000" step="1" value="100"></label><label>Assumed CPC (SAR)<input id="sim-cpc" type="number" min="0.01" max="10000" step="0.1" value="5"></label></div><div id="sim-output" class="stats" aria-live="polite"></div><p>If actual CPC were higher, the same amount would buy fewer clicks. A click is not a lead. SAR100 is currently the total marketing allowance, so actual media may be lower.</p><p>For most unchanged-budget campaigns, the average-daily-budget system allows daily variation and uses30.4 for the monthly limit. Budget changes, partial months and other charges require separate checks. <a href="https://support.google.com/google-ads/answer/1704443?hl=en">Google spending guidance ↗</a></p>')+
block('Search-term sorting exercise','<p>Target lesson: VAT reconciliation. Choose how to handle each example before seeing the reasoning.</p><label>Example query <select id="query-choice"><option value="relevant">فرق المبيعات والإقرار الضريبي</option><option value="job">وظائف محاسب ضريبة</option><option value="free">دليل مجاني لمطابقة ضريبة القيمة المضافة</option><option value="case">استشارة اعتراض ضريبي</option></select></label><div class="example" id="query-answer"></div><p>These are invented training queries, not observed searches. <a href="https://support.google.com/google-ads/answer/7478529?hl=en">Match types</a> · <a href="https://support.google.com/google-ads/answer/2472708?hl=en">Search terms report and its limits</a></p>')+
block('Launch decision: every condition needs evidence','<div class="launch-grid">'+['Article live and useful on mobile','Form succeeds and reaches the company','Success event fires once, with correct goals','Relevant keywords and location reviewed','Final ad and landing-page promise agree','Media cap and stopping rules approved'].map((x,i)=>'<div><b>'+String(i+1).padStart(2,'0')+'</b><span>'+x+'</span></div>').join('')+'</div><p>The calendar has separate missions for these checks. A tick in a personal mission checklist does not approve a campaign. Keep the old campaigns paused.</p>');
const stage=i=>{const s=AD_STEPS[i];document.querySelector('#stage-detail').innerHTML='<span class="eyebrow">Step '+(i+1)+' of6</span><h2>'+s[1]+'</h2><p>'+s[2]+'</p><div class="example"><b>Judy’s check:</b> '+s[3]+'</div>';document.querySelectorAll('[data-stage]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.stage)===i)));};document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>stage(Number(b.dataset.stage)));stage(0);
const calc=()=>{const b=Number(document.querySelector('#sim-budget').value),c=Number(document.querySelector('#sim-cpc').value),out=document.querySelector('#sim-output');if(!Number.isFinite(b)||!Number.isFinite(c)||b<0||c<=0||b>100000||c>10000){out.textContent='Enter a nonnegative budget and a positive CPC within the shown limits.';return;}out.innerHTML='<div class="stat"><strong>'+Math.floor(b/c)+'</strong><span>Illustrative whole clicks</span></div><div class="stat"><strong>'+((Math.floor(b/30.4*100))/100).toFixed(2)+'</strong><span>SAR average daily equivalent, rounded down</span></div><div class="stat"><strong>Unknown</strong><span>Qualified enquiries; no assumed conversion rate</span></div>';};document.querySelector('#sim-budget').oninput=calc;document.querySelector('#sim-cpc').oninput=calc;calc();
const q={relevant:'Relevant hypothesis: the reader appears to need the explanation. Verify that the actual article answers this mismatch question.',job:'Likely irrelevant to this pilot: the person wants employment. Review a jobs-related negative with the right match scope; do not remove unrelated valuable terms accidentally.',free:'Potentially relevant: the article is free. Do not automatically exclude “free” when free education is the ad promise.',case:'Different intent: the reader wants objection advice. It may fit another approved service campaign, but not this reconciliation article. Keep the first pilot focused.'};const pick=()=>document.querySelector('#query-answer').textContent=q[document.querySelector('#query-choice').value];document.querySelector('#query-choice').onchange=pick;pick();
}

