
const MISSIONS=[
['M01','Before launch','CEO + Omar','Confirm the business focus','30 min','Agree priority audience, actual services and service area.','A one-page brief with one primary buyer and three recurring questions.','Do not use assumed service coverage or unverified credentials.','#brief'],
['M02','Before launch','Judy','Review tomorrow’s pack','30 min','Open the three slides and caption together on a phone. Send exact files for review.','CEO feedback recorded privately; spelling, formula and scope checked.','Approval is not recorded in this desk.','#tomorrow'],
['M03','Before launch','Judy','Publish the one approved carousel','20 min + replies','Use 01–03 in order. Preserve the limitation. No link or boost.','Published URL and final crop shared with Omar after approval.','Only this organic post is allowed before the website is ready.','#publish'],
['M04','Before launch','Judy','Listen before making more','20 min','Record the general questions and saves/shares at 24h and seven days.','One observation and one improvement; no invented reach target.','Do not interpret one post as proof of a winning strategy.','#learn'],
['M05','Before launch','CEO','Supply real trust evidence','45 min','Provide approved team names, roles, headshots, licence details and permission to display them.','Verified evidence folder and approved descriptions, stored privately.','Never invent certificates, testimonials or case outcomes.','#ceo'],
['M06','Before launch','Omar','Clear the website launch gate','60–90 min','Test Arabic mobile reading, service links, enquiry form, inbox delivery and privacy flow.','Successful test evidence; correct article URLs and reliable submission event.','Do not launch article-led posts or paid ads while this is unresolved.','#ads-lab'],
['M07','Cycle 1','Omar','Make the Zakat article the anchor','90 min','Check the existing article against sources and CEO feedback. Add a worked organisational example and useful service route.','Reviewed article with direct answer, limitations and working internal links.','Do not present a file-organisation checklist as official filing requirements.','#campaign/zakat-file-preparation'],
['M08','Cycle 1','Judy','Adapt the anchor for one channel','45 min','Choose Instagram carousel or LinkedIn explanation based on the reader. Verify its exact article destination.','Final caption, numbered visuals, alt text and approved CTA.','Website gate and content review must be cleared.','#publish'],
['M09','Cycle 1','Judy','Publish and record the journey','30 min','Use a verified profile/Story route on Instagram or direct article link on LinkedIn.','Post URL, tagged external visits and useful questions recorded privately.','A feed caption URL is not a dependable clickable route.','#learn'],
['M10','Cycle 1','Omar + Judy','Run a cover comprehension check','30 min','Show two cover drafts to three willing colleagues; ask what lesson they expect.','Record paraphrased answers and choose the clearer cover.','This is qualitative feedback, not a statistically valid split test.','#growth'],
['M11','Cycle 1','Omar','Build a source and expert habit','30 min','Verify each tax claim and applicable scope. Ask the CEO to review the substantive example.','Claim, source, scope, reviewer and version recorded for the anchor.','A competitor article is not a tax-law authority.','#competitors'],
['M12','Cycle 2','Omar','Strengthen VAT reconciliation','90 min','Improve the existing guide with period/scope comparison and one concrete next action.','Reviewed article and distinct social lesson, without repeating the Zakat creative.','The sample must not imply every mismatch is an error.','#campaign/vat-reconciliation-checklist'],
['M13','Cycle 2','Judy','Test one reach hypothesis','45 min','Compare a question-led cover with a calculation-led cover across comparable approved posts.','A written hypothesis, fixed metric and one next decision.','Organic comparisons have confounders; record them.','#growth'],
['M14','Cycle 2','Judy + Omar','Create a short explainer brief','45 min','Storyboard one approved lesson: question, demonstration, answer, limitation.','Reviewed spoken Arabic, on-screen text, shots and accessibility notes.','No need to force a video if a static example teaches it better.','#growth'],
['M15','Cycle 2','Omar','Verify the invoice article','60 min','Check current ZATCA sources, applicability and publication before sharing its link.','Live article passes mobile and link review; CEO approves its claims.','Prepared URL does not equal a published page.','#campaign/pdf-vs-electronic-invoice'],
['M16','Cycle 3','Omar','Research a small Search pilot','45 min','Use Keyword Planner for the agreed region and language. Record demand ranges and cost estimates.','One tightly related keyword group, negatives and matching article.','Do not treat our seed phrases as measured demand.','#ads-lab'],
['M17','Cycle 3','Omar','Validate goals before bidding','60 min','Test one successful form submission, failed validation and reload. Inspect event counting and email receipt.','One real success fires once; failure and reload do not create false leads.','Keep page reads and call clicks separate from confirmed enquiries.','#ads'],
['M18','Cycle 3','CEO + Omar','Approve the pilot allowance','20 min','Separate media, production, subscriptions and taxes within the marketing allowance.','A written media cap, duration, stop conditions and monitoring owner.','SAR100 total marketing is not automatically SAR100 ad spend.','#ads-lab'],
['M19','Cycle 3','Omar + Judy','Prepare the fresh Search draft','60 min','Use the lab, then inspect real settings in Ads: goal, location, terms, copy, URL and budget.','A reviewed draft ready for an explicit launch decision.','Keep old campaigns paused; drafting does not authorize spend.','#ads'],
['M20','Cycle 4','Omar + Judy','Decide what earns another cycle','45 min','Review content learning, article use, actual enquiries and any approved pilot costs.','Keep / revise / stop decisions with evidence and a next owner.','More impressions alone do not justify a budget increase.','#learn']
];
function missionCalendar(){
 main.innerHTML=head('Mission calendar','A clear next action for every working day.','Twenty missions across preparation and four working cycles. Cycles begin when their dependencies are ready; they are not automatic publishing dates.')+
 '<div class="notice">Preparation can continue now. Only the reviewed standalone VAT carousel may publish before launch. Progress below is a personal checklist stored in this browser—not shared team status or CEO approval.</div><div class="toolbar"><select id="phase" aria-label="Mission phase"><option>All phases</option>'+[...new Set(MISSIONS.map(m=>m[1]))].map(p=>'<option>'+p+'</option>').join('')+'</select><select id="mission-owner" aria-label="Mission owner"><option>All owners</option><option>Judy</option><option>Omar</option><option>CEO</option></select><button id="export-missions">Export my progress</button><a class="button" href="mission-calendar.csv" download>Download all missions</a></div><div id="mission-progress" role="status"></div><div id="mission-board"></div>';
 let progress={};try{progress=JSON.parse(localStorage.getItem('mada-missions-v1')||'{}')}catch{}
 if(!progress||typeof progress!=='object'||Array.isArray(progress))progress={}; const paint=()=>{const p=document.querySelector('#phase').value,o=document.querySelector('#mission-owner').value;const rows=MISSIONS.filter(m=>(p==='All phases'||p===m[1])&&(o==='All owners'||m[2].includes(o)));document.querySelector('#mission-progress').textContent=MISSIONS.filter(m=>progress[m[0]]).length+' of '+MISSIONS.length+' personally marked complete';
 document.querySelector('#mission-board').innerHTML=rows.map(m=>'<article class="mission-task"><div class="mission-meta"><span class="pill">'+m[0]+' · '+m[1]+'</span><span>'+m[2]+' · '+m[4]+'</span></div><h2>'+m[3]+'</h2><p>'+m[5]+'</p><details><summary>Deliverable, completion check and dependency</summary><p><b>Done means:</b> '+m[6]+'</p><p><b>Dependency / caution:</b> '+m[7]+'</p><a href="'+m[8]+'">Open the relevant guide →</a></details><label class="done-toggle"><input type="checkbox" data-mission="'+m[0]+'" '+(progress[m[0]]?'checked':'')+'> I have completed this task</label></article>').join('');
 document.querySelectorAll('[data-mission]').forEach(x=>x.onchange=()=>{progress[x.dataset.mission]=x.checked;try{localStorage.setItem('mada-missions-v1',JSON.stringify(progress))}catch{}paint()});};
 document.querySelector('#phase').onchange=paint;document.querySelector('#mission-owner').onchange=paint;document.querySelector('#export-missions').onclick=()=>{const blob=new Blob([JSON.stringify({note:'Personal browser checklist; not approval or shared status',missions:MISSIONS.map(m=>({id:m[0],task:m[3],owner:m[2],complete:!!progress[m[0]]}))},null,2)],{type:'application/json'});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='mada-mission-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};paint();
}
function competitors(){
 main.innerHTML=head('Competitor evidence','Compete on clarity, proof and a useful next step.','Focused review of four accessible competitor pages. This is a website-content comparison, not a ranking, market-share or advertising-performance audit.')+
 '<div class="benchmark-grid">'+[
 ['BDO Saudi Arabia','Expert-led education','Its CFO audit-readiness article names a tax leader, structures business risks into sections and links to a specialist contact.','Give Mada articles an approved named reviewer, a concrete example and a relevant next step. Do not repeat the article’s regulatory predictions as established law.','https://www.bdoalamri.com/en-gb/insights/zatca-compliance-2026-the-cfo-s-guide-to-audit-readiness-in-saudi-arabia'],
 ['RSM Saudi Arabia','Service-to-contact path','Its tax and Zakat page groups services and includes an on-page contact form.','Pair each Mada service with a plain-language scope, useful preparation guide and tested enquiry form. A visible form alone does not prove delivery works.','https://www.rsm.global/saudiarabia/service/tax-zakat-services'],
 ['Adaa','Local service breadth','The accessible English homepage lists tax service categories, consultation CTAs and a Jeddah contact address.','Make the local service area and enquiry route clear. Keep service explanations concise and support all credentials with evidence. Its testimonials and scale figures are company claims, not independently verified findings.','https://adaa-consulting.com.sa/en/'],
 ['SJB','Answers to buying questions','The page includes service descriptions, FAQs on cost and remote coverage, and consultation links.','Explain Mada’s process, coverage and what happens after an enquiry. Publish pricing only if the CEO approves it; never borrow competitor credentials or absolute outcome promises.','https://www.sjb.sa/en/tax-consultant']
 ].map(r=>'<section class="panel"><span class="eyebrow">'+r[1]+'</span><h2>'+r[0]+'</h2><p><b>Observed:</b> '+r[2]+'</p><p><b>Mada action:</b> '+r[3]+'</p><a href="'+r[4]+'" target="_blank" rel="noopener">Inspect source page ↗</a></section>').join('')+'</div>'+
 block('Where Mada can be meaningfully different','<div class="journey"><div><b>Understand in 30 seconds</b><span>Direct answer + a worked business example</span></div><div><b>Trust the explanation</b><span>Official source + applicability + real reviewer</span></div><div><b>Know what to do next</b><span>Checklist + relevant service + reliable contact</span></div></div><p>This is a proposed position to test with readers, not proof we outperform these firms.</p>')+
 block('What this review cannot tell us','<p>We did not obtain competitor analytics, spend, leads or search positions. No consistent social-post sample was inspected, so this is not a social engagement comparison. Do not infer success from a polished site or public likes.</p><p>For a future social audit, use the same sample rule for each accessible account: up to 12 most recent posts, recording the actual number available, format, hook, lesson, expert presence and destination. Compare observable practices; leave reach and sales unknown.</p>')+
 block('Priority topic queue','<ol><li><b>VAT-inclusive arithmetic:</b> immediate standalone usefulness; already prepared.</li><li><b>Zakat review-file preparation:</b> practical document handoff; confirm the organisational scope.</li><li><b>VAT reconciliation:</b> one cause of mismatch at a time, linked to the full guide.</li><li><b>Electronic invoice versus PDF:</b> verify current official requirements before publication.</li><li><b>First consultation:</b> explain what happens, what to prepare and how private documents are handled.</li></ol><p>Priority is provisional until the CEO supplies recurring customer questions and Keyword Planner/Search Console supply first-party search evidence. ZATCA is the rule source and a reader alternative, not a commercial competitor.</p>');
}
function ceoDesk(){main.innerHTML=head('CEO decisions','Ask for evidence that makes the work stronger.','Collect these privately. The public desk contains the request list, not confidential documents.')+
block('Business and buyer decisions','<ol><li>Which three services should marketing prioritise, and which enquiries should we decline?</li><li>Who is the main buyer: business owner, finance manager or another role?</li><li>Which cities and industries can Mada actually serve?</li><li>What are the five most common questions before a client engages?</li><li>Can we publish a consultation process, response expectation or starting price? What wording is approved?</li></ol>')+
block('Trust assets and permissions','<ol><li>Legal company name in Arabic and English; approved brand files.</li><li>Licence/certificate issuer, number, scope and permitted public display.</li><li>Team names, roles, accurate biographies and consented professional headshots.</li><li>Real office photos with permission to use them.</li><li>Written permission for any client logo, testimonial or anonymised case example.</li><li>Named reviewer for each technical article and a realistic review turnaround.</li></ol>')+
block('Delivery and measurement','<ol><li>Which company inbox receives enquiries and who checks it?</li><li>What counts as a qualified enquiry for Mada?</li><li>Who follows up, in what working hours, and what response time can we actually meet?</li><li>How is the SAR100 allowance split between media and production? Are taxes and tools included?</li><li>Who can approve a pilot, pause it and authorize a larger test?</li></ol><p>Mark each response confirmed / awaiting / not available. Missing evidence becomes a mission; it must not be replaced by invented website copy.</p>');
}


